### PR TITLE
Contribution

### PR DESCRIPTION
**Pull request by lazik16**
Hello All!
I want to participate on this project. I am interested in WiFi technology based on MCU.
I like to test and develop project based on your prototype board.

Have nice day.
Jan

### CODE REVIEW

**Comment by kasprik** [comment]
Hello Everybody!
I would like to participate on this interested project. I like to test and develop project based on your prototype board.

**Comment by ZencoreCZ** [comment]
Hello there!
I would like to participate on this interested project. 
I like to test and develop project based on your prototype board.

**Review by YafeiJin — DISMISSED** [review]

**Comment by YafeiJin** [comment]
Welcome & Thanks. This pullrequest involves some changes we don’t expect. More discussion needed

**Comment by YafeiJin** [comment]
For simplicity, currently we only accept the commit on bug fix. Sorry for this...

**Comment by YafeiJin** [comment]
Please create new request for the following commits.
Thanks.

**Pull request closed without merging**
